[[plugins]]
repo = 'roxma/nvim-yarp'
if = '! has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '! has("nvim")'

[[plugins]]
repo = 'skanehira/docker.vim'
if = '! has("nvim")'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']
hook_add = 'source ~/dotfiles/.vim/lazys/ruby.vim'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'uji/neoterm-rspec.vim'
on_ft = ['ruby']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'elmcast/elm-vim'
on_ft = ['elm']

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']
